title: Tóta Van Helzing
description: Tóta's website
baseurl:
logo: /assets/img/tota.png
social:
  links:
    - https://www.facebook.com/totavanhelzing/
    - https://www.instagram.com/totavanhelzing/
collections:
  home_images:
    output: true
  sweaters:
    output: true
    permalink: /shop/:path/
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/img/tota.png
  -
    scope:
      path: ""
      type: "sweaters"
    values:
      layout: "sweater"
      author: "Tóta Van Helzing"
sass:
  sass_dir: _scss
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag